name: Code Standards
on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]
jobs:
  eslint:
    name: JS Code Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - uses: sibiraj-s/action-eslint@v1
        with:
          eslintArgs: '--quiet'
          extensions: 'js, jsx, ts, tsx'
          annotations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
