name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Installing NPM packages
        run: yarn

      - name: Get File(s) Changed
        id: get_files_changed
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: Files(s) Changes
        run: |
          echo Added files: ${{ steps.get_files_changed.outputs.files_added }}
          echo Changed files: ${{ steps.get_files_changed.outputs.files_modified }}
          echo Removed files: ${{ steps.get_files_changed.outputs.files_removed }}
