name: Tests

on:
  push:
    branches: [master, main, develop]

  pull_request:
    branches: [master, main, develop]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn
          config-file: cypress.dev.json
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
