name: Unit and User Flow Testing

on:
  push:
    branches: [master, main, develop]

  pull_request:
    branches: [master, main, develop]

  workflow_run:
    workflows: ['Linting']
    types:
      - completed

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Installing NPM packages
        run: yarn

      - name: Run Unit Tests
        run: yarn test:jest

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          config-file: ./cypress.ci.json
          start: yarn test:e2e
          wait-on: 'http://localhost:3099'
          config: baseUrl=http://localhost:3099
