name: Unit and User Flow Testing

on:
  push:
    branches: [master, main, develop]

  pull_request:
    branches: [master, main, develop]

  workflow_run:
    workflows: ['Linting']
    types:
      - completed

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Installing NPM packages
        run: yarn

      - name: Run Unit Tests
        run: yarn test:jest

      - name: Run User Flow Tests
        run: yarn cy:ci
